#' @title Program code collection
#' @description A collection of R program examples
#' @name ggplt-package
#' @docType package
NULL

#' Program code collection
#' 
#' A list containing various R program examples
#' 
#' @export
program_code <- list(
  # Program 1: Triangle Analysis
  program1 = paste0(
    "# Triangle Analysis Program\n",
    "is_valid_triangle <- function(a, b, c) {\n",
    "  return ((a + b > c) & (b + c > a) & (a + c > b))\n",
    "}\n\n",
    "triangle_type <- function(a, b, c) {\n",
    "  if (a == b && b == c) {\n",
    "    return(\"Equilateral\")\n",
    "  } else if (a == b || b == c || a == c) {\n",
    "    return(\"Isosceles\")\n",
    "  } else {\n",
    "    return(\"Scalene\")\n",
    "  }\n",
    "}\n\n",
    "triangle_area <- function(a, b, c) {\n",
    "  s <- (a + b + c) / 2 # Semi-perimeter\n",
    "  area <- sqrt(s * (s - a) * (s - b) * (s - c))\n",
    "  return(area)\n",
    "}\n\n",
    "validate_input <- function(x) {\n",
    "  if (!is.numeric(x) || x <= 0) {\n",
    "    stop(\"Error: Input must be a positive number.\")\n",
    "  }\n",
    "  return(TRUE)\n",
    "}\n\n",
    "# Main code block\n",
    "cat(\"Enter the lengths of the sides of the triangle:\\n\")\n",
    "a <- as.numeric(readline(prompt = \"Side a: \"))\n",
    "b <- as.numeric(readline(prompt = \"Side b: \"))\n",
    "c <- as.numeric(readline(prompt = \"Side c: \"))\n\n",
    "tryCatch({\n",
    "  validate_input(a)\n",
    "  validate_input(b)\n",
    "  validate_input(c)\n",
    "  if (!is_valid_triangle(a, b, c)) {\n",
    "    stop(\"Error: The given sides do not form a valid triangle.\")\n",
    "  }\n",
    "  type_of_triangle <- triangle_type(a, b, c)\n",
    "  cat(\"The triangle is:\", type_of_triangle, \"\\n\")\n",
    "  area_of_triangle <- triangle_area(a, b, c)\n",
    "  cat(\"The area of the triangle is:\", area_of_triangle, \"\\n\")\n",
    "}, error = function(e) {\n",
    "  cat(e$message, \"\\n\")\n",
    "})\n"
  ),

  # Program 2: Vector and Matrix Operations
  program2 = paste0(
    "# Vector and Matrix Operations\n",
    "set.seed(42)\n",
    "random_vector <- runif(20, min = 1, max = 100)\n",
    "cat(\"Original random vector:\\n\", random_vector, \"\\n\")\n\n",
    "# Sort the vector\n",
    "sorted_vector <- sort(random_vector)\n",
    "cat(\"Sorted vector:\\n\", sorted_vector, \"\\n\")\n\n",
    "# Search for a specific value\n",
    "search_value <- 50\n",
    "is_value_present <- any(random_vector == search_value)\n",
    "cat(\"Is\", search_value, \"present in the vector?\", is_value_present, \"\\n\")\n\n",
    "# Find values greater than 60\n",
    "values_greater_than_60 <- random_vector[random_vector > 60]\n",
    "cat(\"Values greater than 60:\\n\", values_greater_than_60, \"\\n\")\n\n",
    "# Create matrix and perform operations\n",
    "matrix_from_vector <- matrix(random_vector, nrow = 4, ncol = 5)\n",
    "cat(\"Matrix from vector:\\n\")\n",
    "print(matrix_from_vector)\n\n",
    "matrix_transpose <- t(matrix_from_vector)\n",
    "matrix_multiplication_result <- matrix_from_vector %*% matrix_transpose\n",
    "cat(\"Matrix multiplication result:\\n\")\n",
    "print(matrix_multiplication_result)\n\n",
    "# Create and manipulate list\n",
    "my_list <- list(\n",
    "  numbers = random_vector,\n",
    "  characters = c(\"A\", \"B\", \"C\", \"D\"),\n",
    "  logical_values = c(TRUE, FALSE, TRUE),\n",
    "  matrix = matrix_from_vector\n",
    ")\n",
    "cat(\"List:\\n\")\n",
    "print(my_list)\n\n",
    "# Subsetting the list (extracting numeric and logical parts)\n",
    "subset_numeric <- my_list$numbers\n",
    "cat(\"Subset (numeric part of the list):\\n\", subset_numeric, \"\\n\")\n\n",
    "subset_logical <- my_list$logical_values\n",
    "cat(\"Subset (logical part of the list):\\n\", subset_logical, \"\\n\")\n\n",
    "# Modify elements in the list (replace the second character with \"Z\")\n",
    "my_list$characters[2] <- \"Z\"\n",
    "cat(\"Modified list of characters:\\n\", my_list$characters, \"\\n\")\n\n",
    "# Apply a function to the numeric part of the list\n",
    "squared_numbers <- my_list$numbers^2\n",
    "cat(\"Squared numbers:\\n\", squared_numbers, \"\\n\")\n\n",
    "# Create a data frame\n",
    "df <- data.frame(\n",
    "  ID = 1:20,\n",
    "  Age = sample(18:65, 20, replace = TRUE),\n",
    "  Score = runif(20, min = 50, max = 100),\n",
    "  Passed = sample(c(TRUE, FALSE), 20, replace = TRUE)\n",
    ")\n",
    "cat(\"Data frame:\\n\")\n",
    "print(df)\n\n",
    "# Filter the data frame\n",
    "filtered_df <- subset(df, Age > 30 & Score > 70)\n",
    "cat(\"Filtered data frame (Age > 30 and Score > 70):\\n\")\n",
    "print(filtered_df)\n\n",
    "# Calculate statistics\n",
    "mean_age <- mean(df$Age)\n",
    "sum_age <- sum(df$Age)\n",
    "var_age <- var(df$Age)\n\n",
    "mean_score <- mean(df$Score)\n",
    "sum_score <- sum(df$Score)\n",
    "var_score <- var(df$Score)\n\n",
    "cat(\"Summary statistics for Age column:\\n\")\n",
    "cat(\"Mean Age:\", mean_age, \"\\n\")\n",
    "cat(\"Sum of Age:\", sum_age, \"\\n\")\n",
    "cat(\"Variance of Age:\", var_age, \"\\n\")\n\n",
    "cat(\"Summary statistics for Score column:\\n\")\n",
    "cat(\"Mean Score:\", mean_score, \"\\n\")\n",
    "cat(\"Sum of Score:\", sum_score, \"\\n\")\n",
    "cat(\"Variance of Score:\", var_score, \"\\n\")\n\n",
    "# Handle missing values\n",
    "df$Score[sample(1:20, 5)] <- NA\n",
    "cat(\"Data frame with missing values:\\n\")\n",
    "print(df)\n\n",
    "# Replace NA values\n",
    "df$Score[is.na(df$Score)] <- mean(df$Score, na.rm = TRUE)\n",
    "cat(\"Data frame after imputation of missing values:\\n\")\n",
    "print(df)\n\n",
    "# Group statistics\n",
    "library(dplyr)\n",
    "grouped_stats <- df %>%\n",
    "  group_by(Passed) %>%\n",
    "  summarise(\n",
    "    mean_score = mean(Score, na.rm = TRUE),\n",
    "    mean_age = mean(Age)\n",
    "  )\n",
    "cat(\"Grouped statistics by Passed status:\\n\")\n",
    "print(grouped_stats)\n"
  ),

  # Program 3: Statistical Analysis
  program3 = paste0(
    "# Statistical Analysis Program\n",
    "library(dplyr)\n",
    "library(ggplot2)\n",
    "library(moments)\n",
    "library(palmerpenguins)\n\n",
    "# Load datasets\n",
    "data(iris)\n",
    "data(penguins)\n\n",
    "# Function to calculate mode\n",
    "calc_mode <- function(x) {\n",
    "  return(as.numeric(names(sort(table(x), decreasing = TRUE))[1]))\n",
    "}\n\n",
    "# Perform Statistical Analysis on Iris Dataset\n",
    "cat(\"----- Iris Dataset Analysis -----\\n\")\n",
    "# Mean\n",
    "iris_mean <- sapply(iris[, 1:4], mean)\n",
    "cat(\"Mean:\\n\", iris_mean, \"\\n\")\n\n",
    "# Median\n",
    "iris_median <- sapply(iris[, 1:4], median)\n",
    "cat(\"Median:\\n\", iris_median, \"\\n\")\n\n",
    "# Mode\n",
    "iris_mode <- sapply(iris[, 1:4], calc_mode)\n",
    "cat(\"Mode:\\n\", iris_mode, \"\\n\")\n\n",
    "# Variance\n",
    "iris_variance <- sapply(iris[, 1:4], var)\n",
    "cat(\"Variance:\\n\", iris_variance, \"\\n\")\n\n",
    "# Standard Deviation\n",
    "iris_sd <- sapply(iris[, 1:4], sd)\n",
    "cat(\"Standard Deviation:\\n\", iris_sd, \"\\n\")\n\n",
    "# Skewness\n",
    "iris_skewness <- sapply(iris[, 1:4], skewness)\n",
    "cat(\"Skewness:\\n\", iris_skewness, \"\\n\")\n\n",
    "# Kurtosis\n",
    "iris_kurtosis <- sapply(iris[, 1:4], kurtosis)\n",
    "cat(\"Kurtosis:\\n\", iris_kurtosis, \"\\n\")\n\n",
    "# Hypothesis Testing (t-test) between Sepal.Length of Setosa and Versicolor\n",
    "setosa <- subset(iris, Species == \"setosa\")$Sepal.Length\n",
    "versicolor <- subset(iris, Species == \"versicolor\")$Sepal.Length\n",
    "t_test <- t.test(setosa, versicolor)\n",
    "print(t_test)\n\n",
    "# Visualization of Iris Dataset\n",
    "# Histogram for Sepal.Length\n",
    "ggplot(iris, aes(x = Sepal.Length)) +\n",
    "  geom_histogram(binwidth = 0.3, fill = \"blue\", color = \"black\") +\n",
    "  ggtitle(\"Histogram of Sepal Length in Iris Dataset\")\n\n",
    "# Boxplot for Sepal.Length across Species\n",
    "ggplot(iris, aes(x = Species, y = Sepal.Length, fill = Species)) +\n",
    "  geom_boxplot() +\n",
    "  ggtitle(\"Boxplot of Sepal Length by Species in Iris Dataset\")\n\n",
    "# Perform Statistical Analysis on Palmer Penguins Dataset\n",
    "cat(\"----- Palmer Penguins Dataset Analysis -----\\n\")\n",
    "# Remove rows with missing values\n",
    "penguins_clean <- na.omit(penguins)\n\n",
    "# Mean\n",
    "penguins_mean <- sapply(penguins_clean[, 3:6], mean, na.rm = TRUE)\n",
    "cat(\"Mean of Palmer Penguins dataset:\\n\", penguins_mean, \"\\n\")\n\n",
    "# Median\n",
    "penguins_median <- sapply(penguins_clean[, 3:6], median, na.rm = TRUE)\n",
    "cat(\"Median of Palmer Penguins dataset:\\n\", penguins_median, \"\\n\")\n\n",
    "# Mode\n",
    "penguins_mode <- sapply(penguins_clean[, 3:6], calc_mode)\n",
    "cat(\"Mode of Palmer Penguins dataset:\\n\", penguins_mode, \"\\n\")\n\n",
    "# Variance\n",
    "penguins_variance <- sapply(penguins_clean[, 3:6], var, na.rm = TRUE)\n",
    "cat(\"Variance of Palmer Penguins dataset:\\n\", penguins_variance, \"\\n\")\n\n",
    "# Standard Deviation\n",
    "penguins_sd <- sapply(penguins_clean[, 3:6], sd, na.rm = TRUE)\n",
    "cat(\"Standard Deviation of Palmer Penguins dataset:\\n\", penguins_sd, \"\\n\")\n\n",
    "# Skewness\n",
    "penguins_skewness <- sapply(penguins_clean[, 3:6], skewness, na.rm = TRUE)\n",
    "cat(\"Skewness of Palmer Penguins dataset:\\n\", penguins_skewness, \"\\n\")\n\n",
    "# Kurtosis\n",
    "penguins_kurtosis <- sapply(penguins_clean[, 3:6], kurtosis, na.rm = TRUE)\n",
    "cat(\"Kurtosis of Palmer Penguins dataset:\\n\", penguins_kurtosis, \"\\n\")\n\n",
    "# Hypothesis Testing (t-test) between flipper_length_mm of Adelie and Gentoo species\n",
    "adelie <- subset(penguins_clean, species == \"Adelie\")$flipper_length_mm\n",
    "gentoo <- subset(penguins_clean, species == \"Gentoo\")$flipper_length_mm\n",
    "t_test_penguins <- t.test(adelie, gentoo)\n",
    "print(t_test_penguins)\n\n",
    "# Visualization of Palmer Penguins Dataset\n",
    "# Histogram for flipper_length_mm\n",
    "ggplot(penguins_clean, aes(x = flipper_length_mm)) +\n",
    "  geom_histogram(binwidth = 3, fill = \"green\", color = \"black\") +\n",
    "  ggtitle(\"Histogram of Flipper Length in Palmer Penguins Dataset\")\n\n",
    "# Boxplot for flipper_length_mm across Species\n",
    "ggplot(penguins_clean, aes(x = species, y = flipper_length_mm, fill = species)) +\n",
    "  geom_boxplot() +\n",
    "  ggtitle(\"Boxplot of Flipper Length by Species in Palmer Penguins Dataset\")\n"
  ),

  # Program 4: Data Cleaning and Preprocessing
  program4 = paste0(
    "# Data Cleaning Program\n",
    "install.packages(\"titanic\")\n",
    "install.packages(\"tidyverse\")\n",
    "install.packages(\"caret\")\n",
    "install.packages(\"ggcorrplot\")\n\n",
    "library(tidyverse)  # For data manipulation\n",
    "library(titanic)    # Titanic dataset\n",
    "library(dplyr)      # Data manipulation\n",
    "library(caret)      # For z-score based outlier detection\n",
    "library(ggcorrplot) # For correlation plot\n\n",
    "# Step 1: Import the Titanic dataset\n",
    "data <- titanic::titanic_train\n\n",
    "# Step 2: Handle missing data\n",
    "# Replace missing 'Age' values with the median\n",
    "data$Age[is.na(data$Age)] <- median(data$Age, na.rm = TRUE)\n\n",
    "# Replace missing 'Embarked' values with the mode\n",
    "mode_embarked <- names(sort(table(data$Embarked), decreasing = TRUE))[1]\n",
    "data$Embarked[is.na(data$Embarked)] <- mode_embarked\n\n",
    "# Step 3: Remove outliers using z-scores\n",
    "numeric_columns <- sapply(data, is.numeric)\n\n",
    "# Calculate z-scores for each numeric column\n",
    "z_scores <- as.data.frame(scale(data[, numeric_columns]))\n\n",
    "# Identify rows that have z-scores greater than 3 or less than -3 (outliers)\n",
    "outlier_condition <- apply(z_scores, 1, function(row) any(abs(row) > 3))\n\n",
    "# Filter out the outliers\n",
    "data_clean <- data[!outlier_condition, ]\n\n",
    "# Step 4: Summarize the dataset before and after cleaning\n",
    "# Summary before cleaning\n",
    "summary_before <- summary(titanic::titanic_train)\n\n",
    "# Summary after cleaning\n",
    "summary_after <- summary(data_clean)\n\n",
    "# Calculate correlation matrix\n",
    "correlation_matrix <- cor(data_clean[, numeric_columns], use = \"complete.obs\")\n\n",
    "# Step 5: Export cleaned data to a new CSV file\n",
    "write.csv(data_clean, \"cleaned_titanic_data.csv\", row.names = FALSE)\n\n",
    "# Display summaries\n",
    "print(\"Summary Before Cleaning:\")\n",
    "print(summary_before)\n\n",
    "print(\"Summary After Cleaning:\")\n",
    "print(summary_after)\n\n",
    "print(\"Correlation Matrix:\")\n",
    "print(correlation_matrix)\n\n",
    "# Step 6: Plot the correlation matrix\n",
    "ggcorrplot(correlation_matrix, method = \"circle\", lab = TRUE, title = \"Correlation Matrix of Titanic Dataset\")\n\n",
    "# Adult Income Dataset Analysis\n",
    "data <- read.csv(\"C:/Users/kalya/Music/Tutorial_Workshop_Amulya/adult/adult.data\", header = FALSE)\n\n",
    "# Assign column names (based on UCI ML repository)\n",
    "colnames(data) <- c(\"age\", \"workclass\", \"fnlwgt\", \"education\", \"education_num\", \n",
    "                    \"marital_status\", \"occupation\", \"relationship\", \"race\", \"sex\", \n",
    "                    \"capital_gain\", \"capital_loss\", \"hours_per_week\", \"native_country\", \"income\")\n\n",
    "# Step 2: Handle missing data\n",
    "# Replace missing '?' values with NA\n",
    "data[data == \"?\"] <- NA\n\n",
    "# Replace missing values in categorical columns with mode\n",
    "replace_mode <- function(x) {\n",
    "  mode_value <- as.character(names(sort(table(x), decreasing = TRUE))[1])\n",
    "  x[is.na(x)] <- mode_value\n",
    "  return(x)\n",
    "}\n\n",
    "data <- data %>%\n",
    "  mutate_if(is.character, replace_mode)\n\n",
    "# Replace missing numeric values with median\n",
    "data <- data %>%\n",
    "  mutate_if(is.numeric, ~ ifelse(is.na(.), median(., na.rm = TRUE), .))\n\n",
    "# Step 3: Remove outliers using z-scores\n",
    "numeric_columns <- sapply(data, is.numeric)\n\n",
    "# Scale numeric columns and filter out rows with z-scores > 3 or < -3\n",
    "data_clean <- data %>%\n",
    "  filter(!apply(as.data.frame(scale(data[, numeric_columns])), 1, function(row) any(abs(row) > 3)))\n\n",
    "# Step 4: Summarize the dataset before and after cleaning\n",
    "# Summary before cleaning\n",
    "data_raw <- read.csv(\"C:/Users/kalya/Music/Tutorial_Workshop_Amulya/adult/adult.data\", header = FALSE)\n",
    "summary_before <- summary(data_raw)\n\n",
    "# Summary after cleaning\n",
    "summary_after <- summary(data_clean)\n\n",
    "# Calculate correlation matrix for numeric columns\n",
    "correlation_matrix <- cor(data_clean[, numeric_columns], use = \"complete.obs\")\n\n",
    "# Step 5: Export cleaned data to a new CSV file\n",
    "write.csv(data_clean, \"cleaned_adult_income_data.csv\", row.names = FALSE)\n\n",
    "# Display summaries\n",
    "cat(\"Summary Before Cleaning:\\n\")\n",
    "print(summary_before)\n\n",
    "cat(\"Summary After Cleaning:\\n\")\n",
    "print(summary_after)\n\n",
    "cat(\"Correlation Matrix:\\n\")\n",
    "print(correlation_matrix)\n\n",
    "# Step 7: Plot the correlation matrix\n",
    "ggcorrplot(correlation_matrix, method = \"circle\", lab = TRUE, \n",
    "           title = \"Correlation Matrix of Adult Income Dataset\")\n"
  ),

  # Program 5: Data Manipulation and Transformation
  program5 = paste0(
    "# Data Manipulation and Transformation Program\n",
    "install.packages(\"zoo\")\n",
    "install.packages(\"nycflights13\")\n",
    "library(dplyr)\n",
    "library(nycflights13)\n",
    "library(ggplot2)\n",
    "library(zoo)\n\n",
    "# Load Star Wars dataset\n",
    "data(\"starwars\")\n",
    "head(starwars)\n\n",
    "# Task 1: Select, Filter, and Arrange\n",
    "starwars_filtered <- starwars %>%\n",
    "  select(name, species, height, mass) %>%\n",
    "  filter(!is.na(species) & !is.na(height) & height > 100) %>%\n",
    "  arrange(desc(height))\n\n",
    "# Visualization\n",
    "ggplot(starwars_filtered, aes(x = reorder(name, -height), y = height, fill = species)) +\n",
    "  geom_bar(stat = \"identity\") +\n",
    "  coord_flip() +\n",
    "  labs(title = \"Height of Star Wars Characters\", x = \"Character\", y = \"Height (cm)\") +\n",
    "  theme_minimal()\n\n",
    "# Task 2: Group and Summarize\n",
    "species_summary <- starwars %>%\n",
    "  group_by(species) %>%\n",
    "  summarize(\n",
    "    avg_height = mean(height, na.rm = TRUE),\n",
    "    avg_mass = mean(mass, na.rm = TRUE),\n",
    "    count = n()\n",
    "  ) %>%\n",
    "  arrange(desc(count))\n\n",
    "# Task 3: Create New Column\n",
    "starwars_classified <- starwars %>%\n",
    "  mutate(height_category = ifelse(height > 180, \"Tall\", \"Short\"))\n\n",
    "# Task 4: Join Operations\n",
    "data(\"flights\")\n",
    "data(\"airlines\")\n",
    "flights_inner_join <- flights %>%\n",
    "  inner_join(airlines, by = \"carrier\")\n\n",
    "# Task 5: Rolling Averages\n",
    "flights_rolling <- flights %>%\n",
    "  arrange(year, month, day) %>%\n",
    "  mutate(\n",
    "    arr_delay = ifelse(is.na(arr_delay), 0, arr_delay),\n",
    "    rolling_avg_delay = rollmean(arr_delay, 5, fill = NA),\n",
    "    cumulative_delay = cumsum(arr_delay)\n",
    "  )\n"
  ),

  # Program 6: Data Visualization
  program6 = paste0(
    "# Data Visualization Program\n",
    "install.packages(\"ggplot2\")\n",
    "install.packages(\"reshape2\")\n\n",
    "library(ggplot2)\n",
    "library(reshape2)\n",
    "library(dplyr)\n\n",
    "# Task 1: Scatter Plot with Regression Line and Confidence Intervals\n",
    "data(\"mpg\")\n\n",
    "# Creating a scatter plot with regression line and confidence intervals\n",
    "ggplot(mpg, aes(x = displ, y = hwy, color = class)) +\n",
    "  geom_point(size = 3, alpha = 0.7) +\n",
    "  geom_smooth(method = \"lm\", se = TRUE, linetype = \"dashed\", color = \"black\", size = 1) +\n",
    "  labs(\n",
    "    title = \"Scatter Plot of Engine Displacement vs Highway MPG with Regression Line\",\n",
    "    x = \"Engine Displacement (L)\",\n",
    "    y = \"Highway Miles per Gallon\",\n",
    "    color = \"Vehicle Class\"\n",
    "  ) +\n",
    "  theme_bw() +\n",
    "  theme(\n",
    "    plot.title = element_text(hjust = 0.5, size = 16, face = \"bold\"),\n",
    "    axis.title = element_text(size = 14),\n",
    "    legend.position = \"bottom\"\n",
    "  )\n\n",
    "# Task 2: Multi-panel Plot using Faceting\n",
    "ggplot(mpg, aes(x = displ, y = hwy)) +\n",
    "  geom_point(color = \"darkgreen\", size = 2) +\n",
    "  facet_wrap(~ class, ncol = 3) +\n",
    "  labs(\n",
    "    title = \"Faceted Scatter Plot by Vehicle Class\",\n",
    "    x = \"Engine Displacement (L)\",\n",
    "    y = \"Highway Miles per Gallon\"\n",
    "  ) +\n",
    "  theme_minimal() +\n",
    "  theme(\n",
    "    strip.text = element_text(size = 12, face = \"italic\"),\n",
    "    plot.title = element_text(hjust = 0.5, size = 16)\n",
    "  )\n\n",
    "# Task 3: Heatmap of Correlation Matrix\n",
    "data(\"diamonds\")\n",
    "cor_matrix <- cor(diamonds[, sapply(diamonds, is.numeric)], use = \"complete.obs\")\n",
    "cor_data <- melt(cor_matrix)\n\n",
    "ggplot(cor_data, aes(Var1, Var2, fill = value)) +\n",
    "  geom_tile(color = \"white\") +\n",
    "  scale_fill_gradient2(\n",
    "    low = \"blue\", high = \"red\", mid = \"white\",\n",
    "    midpoint = 0, limit = c(-1, 1), space = \"Lab\",\n",
    "    name = \"Correlation\"\n",
    "  ) +\n",
    "  labs(\n",
    "    title = \"Heatmap of Correlation Matrix for Diamonds Dataset\",\n",
    "    x = \"Variables\", y = \"Variables\"\n",
    "  ) +\n",
    "  theme_minimal() +\n",
    "  theme(\n",
    "    axis.text.x = element_text(angle = 45, hjust = 1, size = 12),\n",
    "    axis.text.y = element_text(size = 12),\n",
    "    plot.title = element_text(hjust = 0.5, size = 16)\n",
    "  )\n\n",
    "# Task 4: Customize Plot Aesthetics\n",
    "ggplot(mpg, aes(x = displ, y = hwy, color = class)) +\n",
    "  geom_point(size = 3, shape = 21, fill = \"lightblue\", alpha = 0.8) +\n",
    "  theme_light() +\n",
    "  scale_color_brewer(palette = \"Set2\") +\n",
    "  labs(\n",
    "    title = \"Customized Scatter Plot with Aesthetic Enhancements\",\n",
    "    x = \"Engine Displacement (L)\",\n",
    "    y = \"Highway Miles per Gallon\",\n",
    "    color = \"Class\"\n",
    "  ) +\n",
    "  theme(\n",
    "    plot.title = element_text(face = \"bold\", size = 18),\n",
    "    axis.title.x = element_text(size = 14),\n",
    "    axis.title.y = element_text(size = 14),\n",
    "    legend.background = element_rect(fill = \"gray90\")\n",
    "  )\n\n",
    "# Task 5: Annotate Plots and Save as Image Files\n",
    "annotated_plot <- ggplot(mpg, aes(x = displ, y = hwy)) +\n",
    "  geom_point(color = \"purple\", size = 3) +\n",
    "  annotate(\"text\", x = 4, y = 40, label = \"High Efficiency Zone\", \n",
    "           color = \"red\", size = 5, fontface = \"bold\", angle = 15) +\n",
    "  annotate(\"rect\", xmin = 2, xmax = 4, ymin = 30, ymax = 45, \n",
    "           alpha = 0.2, fill = \"yellow\", color = \"orange\") +\n",
    "  labs(\n",
    "    title = \"Annotated Scatter Plot with Highlighted Zone\",\n",
    "    x = \"Engine Displacement (L)\",\n",
    "    y = \"Highway Miles per Gallon\"\n",
    "  ) +\n",
    "  theme_classic() +\n",
    "  theme(plot.title = element_text(hjust = 0.5))\n\n",
    "# Save the annotated plot\n",
    "ggsave(\"annotated_scatter_plot_expanded.png\", annotated_plot, \n",
    "       width = 10, height = 8, dpi = 300)\n"
  ),

  # Program 7: Regression Analysis
  program7 = paste0(
    "# Regression Analysis Program\n",
    "library(caret)\n",
    "library(pROC)\n",
    "install.packages(\"MASS\")\n",
    "install.packages(\"car\")\n",
    "install.packages(\"corrplot\")\n",
    "library(MASS)\n",
    "library(ggplot2)\n",
    "library(car)\n",
    "library(dplyr)\n",
    "library(corrplot)\n\n",
    "# Load Boston Housing dataset\n",
    "data(\"Boston\")\n",
    "head(Boston)\n\n",
    "# Preprocessing\n",
    "cat(\"Missing values:\", sum(is.na(Boston)), \"\\n\")\n",
    "summary(Boston)\n",
    "boxplot(Boston$medv, main = \"Boxplot of Median Value of Homes\")\n",
    "Boston <- Boston %>% filter(medv < 50)\n\n",
    "# Feature Selection\n",
    "cor_matrix <- cor(Boston)\n",
    "corrplot(cor_matrix, method = \"circle\")\n\n",
    "# Simple Linear Regression\n",
    "simple_model <- lm(medv ~ lstat, data = Boston)\n",
    "summary(simple_model)\n\n",
    "# Multiple Linear Regression\n",
    "multiple_model <- lm(medv ~ lstat * rm, data = Boston)\n",
    "summary(multiple_model)\n\n",
    "# Model Performance\n",
    "adjusted_R2 <- summary(multiple_model)$adj.r.squared\n",
    "AIC_value <- AIC(multiple_model)\n",
    "BIC_value <- BIC(multiple_model)\n\n",
    "cat(\"Adjusted R^2:\", adjusted_R2, \"\\n\")\n",
    "cat(\"AIC:\", AIC_value, \"\\n\")\n",
    "cat(\"BIC:\", BIC_value, \"\\n\")\n\n",
    "# Model Diagnostics\n",
    "plot(multiple_model, which = 1)\n",
    "plot(multiple_model, which = 2)\n\n",
    "# Cross-Validation\n",
    "set.seed(123)\n",
    "train_control <- trainControl(method = \"cv\", number = 10)\n",
    "cv_model <- train(medv ~ lstat * rm, data = Boston,\n",
    "                  method = \"lm\",\n",
    "                  trControl = train_control)\n",
    "print(cv_model)\n\n",
    "# ROC Curve Analysis\n",
    "Boston$medv_class <- ifelse(Boston$medv >= 25, 1, 0)\n",
    "logistic_model <- glm(medv_class ~ lstat * rm, data = Boston, family = \"binomial\")\n",
    "pred_probs <- predict(logistic_model, type = \"response\")\n",
    "roc_curve <- roc(Boston$medv_class, pred_probs)\n",
    "# Plot ROC curve with specific formatting\n",
    "plot(roc_curve, main = \"ROC Curve for Logistic Regression Model\", col = \"blue\")\n",
    "abline(a = 0, b = 1, lty = 2, col = \"red\") # Diagonal line for reference\n",
    "cat(\"AUC:\", auc(roc_curve), \"\\n\")\n",
    "\n",
    "# ... (rest of the program) ...\n"
  ),

  # Program 8: Clustering Analysis
  program8 = paste0(
    "# Clustering Analysis Program\n",
    "install.packages(\"rattle\")\n",
    "install.packages(\"cluster\")\n",
    "install.packages(\"factoextra\")\n\n",
    "library(rattle)       # For Wine dataset\n",
    "library(ggplot2)      # For visualization\n",
    "library(cluster)      # For silhouette scores\n",
    "library(factoextra)   # For PCA and clustering visualization\n\n",
    "# Normalize function\n",
    "normalize <- function(data) {\n",
    "  return((data - min(data)) / (max(data) - min(data)))\n",
    "}\n\n",
    "# ==============================\n",
    "# Step 1: Load Wine dataset and normalize\n",
    "# ==============================\n",
    "data(wine, package = \"rattle\")  # Load the Wine dataset from rattle package\n",
    "wine_data <- wine[, -1]         # Remove the class label\n",
    "wine_norm <- as.data.frame(lapply(wine_data, normalize))\n\n",
    "# ==============================\n",
    "# Step 2: Apply PCA\n",
    "# ==============================\n",
    "wine_pca <- prcomp(wine_norm, scale. = TRUE)\n",
    "summary(wine_pca)\n\n",
    "# Reduce to top 2 principal components\n",
    "wine_pca_data <- as.data.frame(wine_pca$x[, 1:2])\n",
    "colnames(wine_pca_data) <- c(\"PC1\", \"PC2\")\n\n",
    "# ==============================\n",
    "# Step 3: Determine the optimal number of clusters (Elbow method)\n",
    "# ==============================\n",
    "elbow_wine <- fviz_nbclust(wine_pca_data, kmeans, method = \"wss\")\n",
    "print(elbow_wine)\n\n",
    "# Step 4: Silhouette analysis\n",
    "silhouette_wine <- fviz_nbclust(wine_pca_data, kmeans, method = \"silhouette\")\n",
    "print(silhouette_wine)\n\n",
    "# ==============================\n",
    "# Step 5: Apply K-means clustering\n",
    "# ==============================\n",
    "set.seed(123)\n",
    "wine_kmeans <- kmeans(wine_pca_data, centers = 3, nstart = 25)\n\n",
    "# Add cluster assignments to PCA data\n",
    "wine_pca_data$cluster <- as.factor(wine_kmeans$cluster)\n\n",
    "# ==============================\n",
    "# Step 6: Visualize clusters\n",
    "# ==============================\n",
    "p1 <- ggplot(wine_pca_data, aes(x = PC1, y = PC2, color = cluster)) +\n",
    "  geom_point(size = 3) +\n",
    "  labs(title = \"K-Means Clustering on Wine Dataset\")\n",
    "print(p1)\n\n",
    "# ==============================\n",
    "# Step 7: Interpret results\n",
    "# ==============================\n",
    "cat(\"Wine Dataset Clustering Results:\\n\")\n",
    "cat(\"Cluster Sizes:\", wine_kmeans$size, \"\\n\")\n\n",
    "# ==============================\n",
    "# Step 8: Repeat for Breast Cancer Wisconsin dataset\n",
    "# ==============================\n\n",
    "# Load Breast Cancer dataset\n",
    "bc_data <- read.csv(\"https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data\", header = FALSE)\n\n",
    "# Exclude ID and class columns\n",
    "bc_features <- bc_data[, -c(1, 2)]\n",
    "bc_norm <- as.data.frame(lapply(bc_features, normalize))\n\n",
    "# Apply PCA\n",
    "bc_pca <- prcomp(bc_norm, scale. = TRUE)\n",
    "summary(bc_pca)\n\n",
    "# Reduce to top 2 principal components\n",
    "bc_pca_data <- as.data.frame(bc_pca$x[, 1:2])\n",
    "colnames(bc_pca_data) <- c(\"PC1\", \"PC2\")\n\n",
    "# Determine optimal number of clusters\n",
    "elbow_bc <- fviz_nbclust(bc_pca_data, kmeans, method = \"wss\")\n",
    "print(elbow_bc)\n\n",
    "silhouette_bc <- fviz_nbclust(bc_pca_data, kmeans, method = \"silhouette\")\n",
    "print(silhouette_bc)\n\n",
    "# Apply K-means clustering\n",
    "set.seed(123)\n",
    "bc_kmeans <- kmeans(bc_pca_data, centers = 2, nstart = 25)\n\n",
    "# Add cluster assignments to PCA data\n",
    "bc_pca_data$cluster <- as.factor(bc_kmeans$cluster)\n\n",
    "# Visualize clusters\n",
    "p2 <- ggplot(bc_pca_data, aes(x = PC1, y = PC2, color = cluster)) +\n",
    "  geom_point(size = 3) +\n",
    "  labs(title = \"K-Means Clustering on Breast Cancer Dataset\")\n",
    "print(p2)\n\n",
    "# Interpret results\n",
    "cat(\"Breast Cancer Dataset Clustering Results:\\n\")\n",
    "cat(\"Cluster Sizes:\", bc_kmeans$size, \"\\n\")\n"
  ),

  # Program 9: Time Series Analysis
  program9 = paste0(
    "# Time Series Analysis Program\n",
    "install.packages(\"forecast\")\n",
    "install.packages(\"TSA\")\n",
    "install.packages(\"tseries\")\n",
    "library(forecast)\n",
    "library(ggplot2)\n",
    "library(TSA)\n",
    "library(tseries)\n\n",
    "# Load AirPassengers dataset\n",
    "data(\"AirPassengers\")\n",
    "air_data <- AirPassengers\n\n",
    "# Exploratory Data Analysis\n",
    "plot(air_data)\n",
    "acf(air_data)\n",
    "pacf(air_data)\n\n",
    "# Decompose time series\n",
    "decomposition <- decompose(air_data)\n",
    "plot(decomposition)\n\n",
    "# Fit ARIMA model\n",
    "adf_test <- adf.test(air_data)\n",
    "if (adf_test$p.value > 0.05) {\n",
    "  air_data <- diff(air_data)\n",
    "}\n",
    "auto_model <- auto.arima(air_data, seasonal = FALSE)\n",
    "forecast_result <- forecast(auto_model, h = 12)\n",
    "plot(forecast_result)\n\n",
    "# Fit SARIMA model\n",
    "auto_sarima <- auto.arima(air_data, seasonal = TRUE)\n",
    "sarima_forecast <- forecast(auto_sarima, h = 12)\n",
    "plot(sarima_forecast)\n\n",
    "# Compare models\n",
    "accuracy(auto_model)\n",
    "accuracy(auto_sarima)\n"
  ),

  # Program 10: Interactive Visualization
  program10 = paste0(
    "# Interactive Visualization Program\n",
    "install.packages(\"plotly\")\n",
    "install.packages(\"gapminder\")\n",
    "library(plotly)\n",
    "library(gapminder)\n",
    "library(dplyr)\n\n",
    "# Load Gapminder dataset\n",
    "data(\"gapminder\")\n\n",
    "# Scatter plot of GDP vs Life Expectancy by Continent\n",
    "scatter_plot <- gapminder %>%\n",
    "  plot_ly(x = ~gdpPercap, y = ~lifeExp, color = ~continent, size = ~pop,\n",
    "          hoverinfo = 'text', text = ~paste(\"Country:\", country, \"<br>GDP per Capita:\", gdpPercap),\n",
    "          type = 'scatter', mode = 'markers') %>%\n",
    "  layout(title = 'GDP vs Life Expectancy by Continent')\n\n",
    "# Bar chart of life expectancy by country in 2007\n",
    "bar_chart <- gapminder %>%\n",
    "  filter(year == 2007) %>%\n",
    "  plot_ly(x = ~country, y = ~lifeExp, type = 'bar',\n",
    "          hoverinfo = 'text', text = ~paste(\"Country:\", country, \"<br>Life Expectancy:\", lifeExp)) %>%\n",
    "  layout(title = 'Life Expectancy by Country in 2007')\n\n",
    "# Line chart showing life expectancy trends over time for Asia\n",
    "line_chart <- gapminder %>%\n",
    "  filter(continent == 'Asia') %>%\n",
    "  plot_ly(x = ~year, y = ~lifeExp, color = ~country, type = 'scatter', mode = 'lines') %>%\n",
    "  layout(title = 'Life Expectancy Trend in Asia')\n\n",
    "# Combine scatter, bar, and line charts into one interactive layout\n",
    "dashboard <- subplot(scatter_plot, bar_chart, line_chart, nrows = 1) %>%\n",
    "  layout(title = 'Gapminder Data Visualization')\n\n",
    "# Display the dashboard\n",
    "dashboard\n"
  )
)

#' Print a specific program
#' 
#' @param program_name Name of the program to print
#' @return Prints the specified program code
#' @examples
#' \dontrun{
#' print_program("program1")
#' }
#' @export
print_program <- function(program_name) {
  if (!program_name %in% names(program_code)) {
    stop("Program not found!")
  }
  cat(program_code[[program_name]], sep = "\n")
}


