#' Program code collection
#' 
#' A list containing various R program examples
#' 
#' @export
program_code <- list(
  # Program 1: Triangle Analysis
  program1 = paste0(
    "# Triangle Analysis Program\n",
    "is_valid_triangle <- function(a, b, c) {\n",
    "  return ((a + b > c) & (b + c > a) & (a + c > b))\n",
    "}\n\n",
    "triangle_type <- function(a, b, c) {\n",
    "  if (a == b && b == c) {\n",
    "    return(\"Equilateral\")\n",
    "  } else if (a == b || b == c || a == c) {\n",
    "    return(\"Isosceles\")\n",
    "  } else {\n",
    "    return(\"Scalene\")\n",
    "  }\n",
    "}\n\n",
    "triangle_area <- function(a, b, c) {\n",
    "  s <- (a + b + c) / 2 # Semi-perimeter\n",
    "  area <- sqrt(s * (s - a) * (s - b) * (s - c))\n",
    "  return(area)\n",
    "}\n\n",
    "validate_input <- function(x) {\n",
    "  if (!is.numeric(x) || x <= 0) {\n",
    "    stop(\"Error: Input must be a positive number.\")\n",
    "  }\n",
    "  return(TRUE)\n",
    "}\n\n",
    "# Main code block\n",
    "cat(\"Enter the lengths of the sides of the triangle:\\n\")\n",
    "a <- as.numeric(readline(prompt = \"Side a: \"))\n",
    "b <- as.numeric(readline(prompt = \"Side b: \"))\n",
    "c <- as.numeric(readline(prompt = \"Side c: \"))\n\n",
    "tryCatch({\n",
    "  validate_input(a)\n",
    "  validate_input(b)\n",
    "  validate_input(c)\n",
    "  if (!is_valid_triangle(a, b, c)) {\n",
    "    stop(\"Error: The given sides do not form a valid triangle.\")\n",
    "  }\n",
    "  type_of_triangle <- triangle_type(a, b, c)\n",
    "  cat(\"The triangle is:\", type_of_triangle, \"\\n\")\n",
    "  area_of_triangle <- triangle_area(a, b, c)\n",
    "  cat(\"The area of the triangle is:\", area_of_triangle, \"\\n\")\n",
    "}, error = function(e) {\n",
    "  cat(e$message, \"\\n\")\n",
    "})\n"
  ),

  # Program 2: Vector and Matrix Operations
  program2 = paste0(
    "# Vector and Matrix Operations\n",
    "set.seed(42)\n",
    "random_vector <- runif(20, min = 1, max = 100)\n",
    "cat(\"Original random vector:\\n\", random_vector, \"\\n\")\n\n",
    "# Sort the vector\n",
    "sorted_vector <- sort(random_vector)\n",
    "cat(\"Sorted vector:\\n\", sorted_vector, \"\\n\")\n\n",
    "# Search for a specific value\n",
    "search_value <- 50\n",
    "is_value_present <- any(random_vector == search_value)\n",
    "cat(\"Is\", search_value, \"present in the vector?\", is_value_present, \"\\n\")\n\n",
    "# Find values greater than 60\n",
    "values_greater_than_60 <- random_vector[random_vector > 60]\n",
    "cat(\"Values greater than 60:\\n\", values_greater_than_60, \"\\n\")\n\n",
    "# Create matrix and perform operations\n",
    "matrix_from_vector <- matrix(random_vector, nrow = 4, ncol = 5)\n",
    "cat(\"Matrix from vector:\\n\")\n",
    "print(matrix_from_vector)\n\n",
    "matrix_transpose <- t(matrix_from_vector)\n",
    "matrix_multiplication_result <- matrix_from_vector %*% matrix_transpose\n",
    "cat(\"Matrix multiplication result:\\n\")\n",
    "print(matrix_multiplication_result)\n\n",
    "# Create and manipulate list\n",
    "my_list <- list(\n",
    "  numbers = random_vector,\n",
    "  characters = c(\"A\", \"B\", \"C\", \"D\"),\n",
    "  logical_values = c(TRUE, FALSE, TRUE),\n",
    "  matrix = matrix_from_vector\n",
    ")\n",
    "cat(\"List:\\n\")\n",
    "print(my_list)\n"
  ),

  # Program 3: Statistical Analysis
  program3 = paste0(
    "# Statistical Analysis Program\n",
    "library(dplyr)\n",
    "library(ggplot2)\n",
    "library(moments)\n",
    "library(palmerpenguins)\n\n",
    "# Load datasets\n",
    "data(iris)\n",
    "data(penguins)\n\n",
    "# Function to calculate mode\n",
    "calc_mode <- function(x) {\n",
    "  return(as.numeric(names(sort(table(x), decreasing = TRUE))[1]))\n",
    "}\n\n",
    "# Iris Dataset Analysis\n",
    "cat(\"----- Iris Dataset Analysis -----\\n\")\n",
    "iris_mean <- sapply(iris[, 1:4], mean, na.rm = TRUE)\n",
    "iris_median <- sapply(iris[, 1:4], median, na.rm = TRUE)\n",
    "iris_mode <- sapply(iris[, 1:4], calc_mode)\n",
    "iris_variance <- sapply(iris[, 1:4], var, na.rm = TRUE)\n",
    "iris_sd <- sapply(iris[, 1:4], sd, na.rm = TRUE)\n",
    "iris_skewness <- sapply(iris[, 1:4], skewness, na.rm = TRUE)\n",
    "iris_kurtosis <- sapply(iris[, 1:4], kurtosis, na.rm = TRUE)\n\n",
    "# Print results\n",
    "cat(\"Mean:\\n\", iris_mean, \"\\n\")\n",
    "cat(\"Median:\\n\", iris_median, \"\\n\")\n",
    "cat(\"Mode:\\n\", iris_mode, \"\\n\")\n",
    "cat(\"Variance:\\n\", iris_variance, \"\\n\")\n",
    "cat(\"Standard Deviation:\\n\", iris_sd, \"\\n\")\n",
    "cat(\"Skewness:\\n\", iris_skewness, \"\\n\")\n",
    "cat(\"Kurtosis:\\n\", iris_kurtosis, \"\\n\")\n"
  ),

  # Program 4: Data Cleaning and Preprocessing
  program4 = paste0(
    "# Data Cleaning and Preprocessing Program\n",
    "install.packages(\"titanic\")\n",
    "install.packages(\"tidyverse\")\n",
    "install.packages(\"caret\")\n",
    "install.packages(\"ggcorrplot\")\n\n",
    "library(tidyverse)\n",
    "library(titanic)\n",
    "library(dplyr)\n",
    "library(caret)\n",
    "library(ggcorrplot)\n\n",
    "# Load Titanic dataset\n",
    "data <- titanic::titanic_train\n\n",
    "# Handle missing data\n",
    "data$Age[is.na(data$Age)] <- median(data$Age, na.rm = TRUE)\n",
    "mode_embarked <- names(sort(table(data$Embarked), decreasing = TRUE))[1]\n",
    "data$Embarked[is.na(data$Embarked)] <- mode_embarked\n\n",
    "# Remove outliers using z-scores\n",
    "numeric_columns <- sapply(data, is.numeric)\n",
    "z_scores <- as.data.frame(scale(data[, numeric_columns]))\n",
    "outlier_condition <- apply(z_scores, 1, function(row) any(abs(row) > 3))\n",
    "data_clean <- data[!outlier_condition, ]\n\n",
    "# Summarize dataset\n",
    "summary_before <- summary(titanic::titanic_train)\n",
    "summary_after <- summary(data_clean)\n",
    "correlation_matrix <- cor(data_clean[, numeric_columns], use = \"complete.obs\")\n\n",
    "# Export cleaned data\n",
    "write.csv(data_clean, \"cleaned_titanic_data.csv\", row.names = FALSE)\n\n",
    "# Display summaries\n",
    "print(\"Summary Before Cleaning:\")\n",
    "print(summary_before)\n",
    "print(\"Summary After Cleaning:\")\n",
    "print(summary_after)\n",
    "print(\"Correlation Matrix:\")\n",
    "print(correlation_matrix)\n\n",
    "# Plot correlation matrix\n",
    "ggcorrplot(correlation_matrix, method = \"circle\", lab = TRUE, title = \"Correlation Matrix of Titanic Dataset\")\n"
  ),

  # Program 5: Data Manipulation and Transformation
  program5 = paste0(
    "# Data Manipulation and Transformation Program\n",
    "install.packages(\"zoo\")\n",
    "install.packages(\"nycflights13\")\n",
    "library(dplyr)\n",
    "library(nycflights13)\n",
    "library(ggplot2)\n",
    "library(zoo)\n\n",
    "# Load Star Wars dataset\n",
    "data(\"starwars\")\n",
    "head(starwars)\n\n",
    "# Task 1: Select, Filter, and Arrange\n",
    "starwars_filtered <- starwars %>%\n",
    "  select(name, species, height, mass) %>%\n",
    "  filter(!is.na(species) & !is.na(height) & height > 100) %>%\n",
    "  arrange(desc(height))\n\n",
    "# Visualization\n",
    "ggplot(starwars_filtered, aes(x = reorder(name, -height), y = height, fill = species)) +\n",
    "  geom_bar(stat = \"identity\") +\n",
    "  coord_flip() +\n",
    "  labs(title = \"Height of Star Wars Characters\", x = \"Character\", y = \"Height (cm)\") +\n",
    "  theme_minimal()\n\n",
    "# Task 2: Group and Summarize\n",
    "species_summary <- starwars %>%\n",
    "  group_by(species) %>%\n",
    "  summarize(\n",
    "    avg_height = mean(height, na.rm = TRUE),\n",
    "    avg_mass = mean(mass, na.rm = TRUE),\n",
    "    count = n()\n",
    "  ) %>%\n",
    "  arrange(desc(count))\n\n",
    "# Task 3: Create New Column\n",
    "starwars_classified <- starwars %>%\n",
    "  mutate(height_category = ifelse(height > 180, \"Tall\", \"Short\"))\n\n",
    "# Task 4: Join Operations\n",
    "data(\"flights\")\n",
    "data(\"airlines\")\n",
    "flights_inner_join <- flights %>%\n",
    "  inner_join(airlines, by = \"carrier\")\n\n",
    "# Task 5: Rolling Averages\n",
    "flights_rolling <- flights %>%\n",
    "  arrange(year, month, day) %>%\n",
    "  mutate(\n",
    "    arr_delay = ifelse(is.na(arr_delay), 0, arr_delay),\n",
    "    rolling_avg_delay = rollmean(arr_delay, 5, fill = NA),\n",
    "    cumulative_delay = cumsum(arr_delay)\n",
    "  )\n"
  ),

  # Program 6: Data Visualization
  program6 = paste0(
    "# Data Visualization Program\n",
    "install.packages(\"ggplot2\")\n",
    "install.packages(\"reshape2\")\n",
    "library(ggplot2)\n",
    "library(reshape2)\n",
    "library(dplyr)\n\n",
    "# Task 1: Scatter Plot with Regression\n",
    "data(\"mpg\")\n",
    "ggplot(mpg, aes(x = displ, y = hwy)) +\n",
    "  geom_point(aes(color = class)) +\n",
    "  geom_smooth(method = \"lm\", se = TRUE) +\n",
    "  labs(title = \"Highway MPG vs. Engine Displacement\",\n",
    "       x = \"Engine Displacement (L)\",\n",
    "       y = \"Highway MPG\") +\n",
    "  theme_minimal()\n\n",
    "# Task 2: Box Plot\n",
    "ggplot(mpg, aes(x = class, y = hwy, fill = class)) +\n",
    "  geom_boxplot() +\n",
    "  labs(title = \"Highway MPG Distribution by Vehicle Class\") +\n",
    "  theme_minimal() +\n",
    "  theme(axis.text.x = element_text(angle = 45))\n\n",
    "# Task 3: Heatmap\n",
    "data(\"diamonds\")\n",
    "cor_matrix <- cor(select_if(diamonds, is.numeric))\n",
    "ggplot(melt(cor_matrix), aes(Var1, Var2, fill = value)) +\n",
    "  geom_tile() +\n",
    "  scale_fill_gradient2() +\n",
    "  theme_minimal()\n\n",
    "# Task 4: Customized Plot\n",
    "ggplot(mpg, aes(x = displ, y = hwy, color = class)) +\n",
    "  geom_point(size = 3, shape = 21, fill = \"lightblue\", alpha = 0.8) +\n",
    "  theme_light() +\n",
    "  scale_color_brewer(palette = \"Set2\") +\n",
    "  labs(title = \"Customized Scatter Plot\")\n\n",
    "# Task 5: Annotated Plot\n",
    "annotated_plot <- ggplot(mpg, aes(x = displ, y = hwy)) +\n",
    "  geom_point(color = \"purple\", size = 3) +\n",
    "  annotate(\"text\", x = 4, y = 40, label = \"High Efficiency Zone\", color = \"red\") +\n",
    "  annotate(\"rect\", xmin = 2, xmax = 4, ymin = 30, ymax = 45,\n",
    "           alpha = 0.2, fill = \"yellow\")\n",
    "ggsave(\"annotated_plot.png\", annotated_plot)\n"
  ),

  # Program 7: Regression Analysis
  program7 = paste0(
    "# Regression Analysis Program\n",
    "install.packages(\"MASS\")\n",
    "install.packages(\"pROC\")\n",
    "install.packages(\"car\")\n",
    "install.packages(\"corrplot\")\n",
    "library(MASS)\n",
    "library(ggplot2)\n",
    "library(caret)\n",
    "library(car)\n",
    "library(pROC)\n",
    "library(dplyr)\n",
    "library(corrplot)\n\n",
    "# Load Boston Housing dataset\n",
    "data(\"Boston\")\n",
    "head(Boston)\n\n",
    "# Preprocessing\n",
    "cat(\"Missing values:\", sum(is.na(Boston)), \"\\n\")\n",
    "summary(Boston)\n",
    "boxplot(Boston$medv, main = \"Boxplot of Median Value of Homes\")\n",
    "Boston <- Boston %>% filter(medv < 50)\n\n",
    "# Feature Selection\n",
    "cor_matrix <- cor(Boston)\n",
    "corrplot(cor_matrix, method = \"circle\")\n\n",
    "# Simple Linear Regression\n",
    "simple_model <- lm(medv ~ lstat, data = Boston)\n",
    "summary(simple_model)\n\n",
    "# Multiple Linear Regression\n",
    "multiple_model <- lm(medv ~ lstat * rm, data = Boston)\n",
    "summary(multiple_model)\n\n",
    "# Model Performance\n",
    "adjusted_R2 <- summary(multiple_model)$adj.r.squared\n",
    "AIC_value <- AIC(multiple_model)\n",
    "BIC_value <- BIC(multiple_model)\n\n",
    "# Model Diagnostics\n",
    "plot(multiple_model, which = 1)\n",
    "plot(multiple_model, which = 2)\n\n",
    "# Cross-Validation\n",
    "set.seed(123)\n",
    "train_control <- trainControl(method = \"cv\", number = 10)\n",
    "cv_model <- train(medv ~ lstat * rm, data = Boston,\n",
    "                  method = \"lm\",\n",
    "                  trControl = train_control)\n",
    "print(cv_model)\n\n",
    "# ROC Curve Analysis\n",
    "Boston$medv_class <- ifelse(Boston$medv >= 25, 1, 0)\n",
    "logistic_model <- glm(medv_class ~ lstat * rm, data = Boston, family = \"binomial\")\n",
    "pred_probs <- predict(logistic_model, type = \"response\")\n",
    "roc_curve <- roc(Boston$medv_class, pred_probs)\n",
    "plot(roc_curve)\n",
    "cat(\"AUC:\", auc(roc_curve), \"\\n\")\n"
  ),

  # Program 8: Clustering Analysis
  program8 = paste0(
    "# Clustering Analysis Program\n",
    "install.packages(\"rattle\")\n",
    "install.packages(\"cluster\")\n",
    "install.packages(\"factoextra\")\n",
    "library(rattle)\n",
    "library(ggplot2)\n",
    "library(cluster)\n",
    "library(factoextra)\n\n",
    "# Normalize function\n",
    "normalize <- function(data) {\n",
    "  return((data - min(data)) / (max(data) - min(data)))\n",
    "}\n\n",
    "# Load and prepare Wine dataset\n",
    "data(wine, package = \"rattle\")\n",
    "wine_data <- wine[, -1]\n",
    "wine_norm <- as.data.frame(lapply(wine_data, normalize))\n\n",
    "# Apply PCA\n",
    "wine_pca <- prcomp(wine_norm, scale. = TRUE)\n",
    "wine_pca_data <- as.data.frame(wine_pca$x[, 1:2])\n\n",
    "# Determine optimal clusters\n",
    "elbow_wine <- fviz_nbclust(wine_pca_data, kmeans, method = \"wss\")\n",
    "silhouette_wine <- fviz_nbclust(wine_pca_data, kmeans, method = \"silhouette\")\n\n",
    "# K-means clustering\n",
    "set.seed(123)\n",
    "wine_kmeans <- kmeans(wine_pca_data, centers = 3, nstart = 25)\n",
    "wine_pca_data$cluster <- as.factor(wine_kmeans$cluster)\n\n",
    "# Visualize clusters\n",
    "ggplot(wine_pca_data, aes(x = PC1, y = PC2, color = cluster)) +\n",
    "  geom_point(size = 3) +\n",
    "  labs(title = \"K-Means Clustering on Wine Dataset\")\n"
  ),

  # Program 9: Time Series Analysis
  program9 = paste0(
    "# Time Series Analysis Program\n",
    "install.packages(\"forecast\")\n",
    "install.packages(\"TSA\")\n",
    "install.packages(\"tseries\")\n",
    "library(forecast)\n",
    "library(ggplot2)\n",
    "library(TSA)\n",
    "library(tseries)\n\n",
    "# Load AirPassengers dataset\n",
    "data(\"AirPassengers\")\n",
    "air_data <- AirPassengers\n\n",
    "# Exploratory Data Analysis\n",
    "plot(air_data)\n",
    "acf(air_data)\n",
    "pacf(air_data)\n\n",
    "# Decompose time series\n",
    "decomposition <- decompose(air_data)\n",
    "plot(decomposition)\n\n",
    "# Fit ARIMA model\n",
    "adf_test <- adf.test(air_data)\n",
    "if (adf_test$p.value > 0.05) {\n",
    "  air_data <- diff(air_data)\n",
    "}\n",
    "auto_model <- auto.arima(air_data, seasonal = FALSE)\n",
    "forecast_result <- forecast(auto_model, h = 12)\n",
    "plot(forecast_result)\n\n",
    "# Fit SARIMA model\n",
    "auto_sarima <- auto.arima(air_data, seasonal = TRUE)\n",
    "sarima_forecast <- forecast(auto_sarima, h = 12)\n",
    "plot(sarima_forecast)\n\n",
    "# Compare models\n",
    "accuracy(auto_model)\n",
    "accuracy(auto_sarima)\n"
  ),

  # Program 10: Interactive Visualization
  program10 = paste0(
    "# Interactive Visualization Program\n",
    "install.packages(\"plotly\")\n",
    "install.packages(\"gapminder\")\n",
    "library(plotly)\n",
    "library(gapminder)\n",
    "library(dplyr)\n\n",
    "# Load Gapminder dataset\n",
    "data(\"gapminder\")\n\n",
    "# Interactive scatter plot\n",
    "scatter_plot <- gapminder %>%\n",
    "  plot_ly(x = ~gdpPercap, y = ~lifeExp, color = ~continent,\n",
    "          size = ~pop, text = ~country, type = \"scatter\", mode = \"markers\") %>%\n",
    "  layout(title = \"GDP vs Life Expectancy by Continent\")\n\n",
    "# Interactive bar chart\n",
    "bar_chart <- gapminder %>%\n",
    "  filter(year == 2007) %>%\n",
    "  plot_ly(x = ~country, y = ~lifeExp, type = \"bar\") %>%\n",
    "  layout(title = \"Life Expectancy by Country in 2007\")\n\n",
    "# Interactive line chart\n",
    "line_chart <- gapminder %>%\n",
    "  filter(continent == \"Asia\") %>%\n",
    "  plot_ly(x = ~year, y = ~lifeExp, color = ~country,\n",
    "          type = \"scatter\", mode = \"lines\") %>%\n",
    "  layout(title = \"Life Expectancy Trend in Asia\")\n\n",
    "# Combine plots into dashboard\n",
    "dashboard <- subplot(scatter_plot, bar_chart, line_chart, nrows = 1) %>%\n",
    "  layout(title = \"Gapminder Data Visualization\")\n\n",
    "# Display dashboard\n",
    "dashboard\n"
  )
)

#' Print a specific program
#' 
#' @param program_name Name of the program to print
#' @export
print_program <- function(program_name) {
  if (!program_name %in% names(program_code)) {
    stop("Program not found!")
  }
  cat(program_code[[program_name]], sep = "\n")
}


